# Generated by Django 6.0.5 on 2026-05-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(upload_to='uploads/%Y-%m-%d'),
        ),
    ]
